# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EU-Ml9vPcXocE-o9OgFgRWe5YC7RbaZ
"""

import openpyxl
from openpyxl.styles import Font
import os

# 請填寫要處理的Excel檔案名稱
wb = openpyxl.load_workbook('train.xlsx')
sheet = wb.worksheets[0]

print("Processing...")

# 第一列會重新命名這樣比較好做後續處理
sheet.cell(1,1).value = ('image_id')
sheet.cell(1,2).value = ('class_name')
sheet.cell(1,3).value = ('class_id')
sheet.cell(1,4).value = ('x_min')
sheet.cell(1,5).value = ('y_min')
sheet.cell(1,6).value = ('x_max')
sheet.cell(1,7).value = ('y_max')

#使用for loop掃描所有A欄品名
x='0'
for rowNum in range(2, sheet.max_row, 1):
    produceName = sheet.cell(rowNum, 1).value
    if produceName != (None) :
        x = produceName
    elif produceName == (None) :
        sheet.cell(rowNum, 1).value = x

for row in range(2, sheet.max_row+1, 1):
    produceName2 = sheet.cell(row, 2).value
    produceName3 = sheet.cell(row, 3).value
    if produceName2 == (None) and produceName3 == (None):
        sheet.cell(row, 2).value = ('No finding')
    if produceName2 == (None) and produceName3 != (None):
        sheet.cell(row, 2).value = produceName3
        sheet.cell(row, 3).value = ('replaced')

for row in range(2, sheet.max_row+1, 1):
    produceName4 = sheet.cell(row, 2).value
    if (produceName4 == ('Nodule')):
        sheet.cell(row, 3).value = int(0)
    elif (produceName4 == ('Consolidation')):
        sheet.cell(row, 3).value = int(1)
    elif (produceName4 == ('Effusion')):
        sheet.cell(row, 3).value = int(2)
    elif (produceName4 == ('Fibrosis')):
        sheet.cell(row, 3).value = int(3)
    elif (produceName4 == ('Emphysema')):
        sheet.cell(row, 3).value = int(4)
    elif (produceName4 == ('Atelectasis')):
        sheet.cell(row, 3).value = int(5)
    elif (produceName4 == ('Fracture')):
        sheet.cell(row, 3).value = int(6)
    elif (produceName4 == ('Pneumothorax')):
        sheet.cell(row, 3).value = int(7)
    elif (produceName4 == ('Mass')):
        sheet.cell(row, 3).value = int(8)
    elif (produceName4 == ('Calcification')):
        sheet.cell(row, 3).value = int(9)
# 將結果另存新檔
wb.save('train_convert_by_python.xlsx')
print("Done!")